endpoint = "https://agent-runtime.generativeai.us-chicago-1.oci.oraclecloud.com" #update if region other than chicago
agent_endpoint_Sentencing = "ocid1.genaiagentendpoint.oc1.us-chicago-1.12345" #update with your endpoint
#agent_endpoint_secondary = "ocid1.genaiagentendpoint.oc1.us-chicago-1.67890" #update with your endpoint if you want to have multiple
llm_endpoint = "https://inference.generativeai.us-chicago-1.oci.oraclecloud.com" #update if region other than chicago
compartment_id = "ocid1.compartment.oc1..12345" #update with your compartment
logo = "Oracle.png" #update if desired, you will need to upload the corresponding image
customer_logo = "ussc-banner-2.png" #update if desired, you will need to upload the corresponding image
user_avatar =  ":material/record_voice_over:" 
assisstant_avatar =  "ussc.png" #update if desired, you will need to upload the corresponding image
llm_avatar =  "o.png" #update if desired, you will need to upload the corresponding image
instruction = "instruction.txt" #not currently being used 
bucket_name = "bucket" #update with your bucket name
namespace_name = "namespace" #update with your namesapce
region = "us-chicago-1" #update if not chicago 
command_r_ocid = "ocid1.generativeaimodel.oc1.us-chicago-1.amaaaaaask7dceyanrlpnq5ybfu5hnzarg7jomak3q6kyhkzjsl4qj24fyoq"
command_plus_ocid = "ocid1.generativeaimodel.oc1.us-chicago-1.amaaaaaask7dceyaodm6rdyxmdzlddweh4amobzoo4fatlao2pwnekexmosq"
llama33_ocid = "ocid1.generativeaimodel.oc1.us-chicago-1.amaaaaaask7dceyajqi26fkxly6qje5ysvezzrypapl7ujdnqfjq6hzo2loq"
llama32_ocid = "ocid1.generativeaimodel.oc1.us-chicago-1.amaaaaaask7dceya2xrydihzvu5pk6vlvfhtbnfapcvwhhugzo7jez4zcnaa"
llama31_ocid = "ocid1.generativeaimodel.oc1.us-chicago-1.amaaaaaask7dceyarleil5jr7k2rykljkhapnvhrqvzx4cwuvtfedlfxet4q"
