endpoint = "https://agent-runtime.generativeai.us-chicago-1.oci.oraclecloud.com" #update if region other than chicago
agent_endpoint_id = "ocid1.genaiagentendpoint....." #update with your endpoint
llm_endpoint = "https://inference.generativeai.us-chicago-1.oci.oraclecloud.com" #update if region other than chicago
compartment_id = "ocid1.compartment....." #update with your compartment
logo = "Oracle.png" #update if desired, you will need to upload the corresponding image 
user_avatar =  ":material/record_voice_over:" #update if desired
assisstant_avatar =  "o.png" #update if desired, you will need to upload the corresponding image 
